- name: Install and configure Nginx
  hosts: proxy
  become: yes
  tasks:
    - name: Install Nginx
      yum:
        name: nginx
        state: present

    - name: Remov default Nginx config file
      file:
        path: /etc/nginx/sites-enabled/Default
        state: absent

    - name: Add custom Nginx config file
      file:
        src: nginx.conf.j2
        dest: /etc/nginx/sites-available/nginx-conf.conf
	user: root
	group: root
	mode: '0644'

    - name: Enable custom nginx conf
      file:
        src /etc/nginx/sites-availble/nginx-conf.conf
	dest: /etc/nginx/sites-enabled/
	state: link
