- hosts: all
  name: Access setup
  roles:
    - { role: user_access_management, tags: user_access_management }
  become: true

- hosts: all
  name: ssh setup
  roles:
  - { role: ssh_setup, tags: ssh_setup}
  become: true

- hosts: all
  name: security_setting
  roles:
  - { role: security_setup, tags: security}
  become: true