- name: ssh root
  hosts: workers
  become: yes
  vars:
    account_name: root
    service_account_home: /root
    ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tasks:
    - name: set up SSH directory
      file:
        path: "{{ account_name }}/.ssh"
        state: directory
        mode: '0700'

    - name: Add SSH key to authorized keys
      authorized_key:
        user: "{{ account_name }}"
        state: present
        key: "{{ ssh_key }}"

    - name: Set up permission for the home directory
      file:
        path: "{{ service_account_home }}"
        state: directory
        owner: "{{ account_name }}"
        mode: '0750'

##-----------------------
    - name: collect sshd configs
      ansible.builtin.find:
        paths: /etc/ssh/sshd_config.d
        patterns: '*.conf'
        file_type: file
      register: collected_info

    - name: update sshd conf
      copy:
        dest: "{{ item.path }}"
        content: "PasswordAuthentication no\n"
      with_items: "{{ collected_info.files }}"
      register: update_result
    
    - name: restart sshd
      service:
        name: sshd
        state: restarted
      when: update_result.changed